package:
    name: shyft_viz
    version: {{ environ.get('SHYFTVIZ_VERSION','1.0.0') }}
    
source:
    # where to find the source-tree
    # in this case we assume it's precompiled
    path: ../
    
build:
    number: 1
    string: py{{CONDA_PY}}_{{PKG_BUILDNUM}}
    
requirements:
    build:
        - python
        - setuptools
        - numpy
    run:
        - python
        - {{ pin_compatible('numpy') }}
        - matplotlib
about:
    home: https://github.com/yisak/shyft_viz
    license: LGPL v.3
    